// miguel garcia 03/19/2026
// Hello Application generated by Gemini

package com.betterstudentteam.thebetterstudentapp;

import atlantafx.base.theme.PrimerDark;
import atlantafx.base.theme.PrimerLight;
import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.ToggleButton;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class HelloApplication extends Application {

    @Override
    public void start(Stage stage1) {
        // --- WINDOW 1: Standard JavaFX (Modena) ---
        Text text1 = new Text("Standard JavaFX");
        ToggleButton btn1 = new ToggleButton("Switch to Dark Mode");
        VBox root1 = new VBox(20, text1, btn1);
        root1.setAlignment(Pos.CENTER);
        Scene scene1 = new Scene(root1, 320, 240);

        btn1.setOnAction(e -> {
            if (btn1.isSelected()) {
                // Force the background and the base color for controls
                root1.setStyle("-fx-background-color: #2b2b2b; -fx-base: #2b2b2b;");
                text1.setStyle("-fx-fill: white;");
                btn1.setText("Switch to Light Mode");
            } else {
                root1.setStyle(""); // Reset to default
                text1.setStyle("-fx-fill: black;");
                btn1.setText("Switch to Dark Mode");
            }
        });

        stage1.setTitle("Standard JavaFX");
        stage1.setScene(scene1);
        stage1.setX(200);
        stage1.show();

        // --- WINDOW 2: AtlantaFX Theme ---
        Stage stage2 = new Stage();
        Text text2 = new Text("AtlantaFX Theme");
        ToggleButton btn2 = new ToggleButton("Switch to Dark Mode");
        VBox root2 = new VBox(20, text2, btn2);
        root2.setAlignment(Pos.CENTER);
        Scene scene2 = new Scene(root2, 320, 240);

        // Start with AtlantaFX Light
        scene2.getStylesheets().add(new PrimerLight().getUserAgentStylesheet());

        btn2.setOnAction(e -> {
            scene2.getStylesheets().clear();
            if (btn2.isSelected()) {
                scene2.getStylesheets().add(new PrimerDark().getUserAgentStylesheet());
                btn2.setText("Switch to Light Mode");
            } else {
                scene2.getStylesheets().add(new PrimerLight().getUserAgentStylesheet());
                btn2.setText("Switch to Dark Mode");
            }
        });

        stage2.setTitle("AtlantaFX");
        stage2.setScene(scene2);
        stage2.setX(600);
        stage2.show();
    }
}